export const perros = [
  {
    id: 1,
    nombre: "Max",
    raza: "Labrador Retriever",
    edad: "2 años",
    tamaño: "Grande",
    genero: "Macho",
    descripcion: "Max es un perro muy juguetón y cariñoso. Le encanta correr y jugar con niños.",
    imagen: "/images/max.jpg",
    adoptado: false,
  },
  {
    id: 2,
    nombre: "Luna",
    raza: "Beagle",
    edad: "1 año",
    tamaño: "Mediano",
    genero: "Hembra",
    descripcion: "Luna es curiosa y llena de energía. Se lleva bien con otros perros y personas.",
    imagen: "/images/luna.jpg",
    adoptado: false,
  },
  {
    id: 3,
    nombre: "Rocky",
    raza: "Bulldog Francés",
    edad: "3 años",
    tamaño: "Pequeño",
    genero: "Macho",
    descripcion: "Rocky es tranquilo y muy leal. Perfecto para vivir en apartamento.",
    imagen: "/images/rocky.jpg",
    adoptado: false,
  },
  {
    id: 4,
    nombre: "Coco",
    raza: "Golden Retriever",
    edad: "4 años",
    tamaño: "Grande",
    genero: "Hembra",
    descripcion: "Coco es muy afectuosa y le encantan los mimos. Ideal para familias.",
    imagen: "/images/coco.jpg",
    adoptado: true,
  },
  {
    id: 5,
    nombre: "Tobi",
    raza: "Mestizo",
    edad: "6 meses",
    tamaño: "Mediano",
    genero: "Macho",
    descripcion: "Tobi es un cachorro lleno de vida. Está buscando su primer hogar.",
    imagen: "/images/tobi.jpg",
    adoptado: false,
  },
]
